<?php
/**
 * Created by PhpStorm.
 * User: 亮仔
 * Date: 2019/10/29
 * Time: 17:14
 */

namespace app\common\model;


use think\Model;

class Category extends Model
{

    //自动添加时间搓

    public function insert($data)
    {
        $data['create_time'] = time();
        $data['update_time'] = time();

        return $this->save($data);

    }

    public function query()
    {
        return parent::select(); // TODO: Change the autogenerated stub
    }

    public function del($id)
    {
        return $this->where('id', $id)->delete();

    }


    public function selectupdates($id)
    {
        return $this->field('cname,thumb,sort')->where('id', $id)->find();
    }


    public function updates($data, $id)
    {
        return $this->where('id', $id)->update($data);
    }


}