<?php
/**
 * Created by PhpStorm.
 * User: 亮仔
 * Date: 2019/10/30
 * Time: 22:31
 */

namespace app\common\model;


use think\Model;

class Goods extends Model
{
    //自动添加时间搓

    public function insert($data)
    {
        $data['create_time'] = time();
        $data['update_time'] = time();

        return $this->save($data);

    }
    public function query()
    {
        return parent::select(); // TODO: Change the autogenerated stub
    }
    public function del($id)
    {
        return $this->where('gid', $id)->delete();

    }
    public function goodsupdates($id)
    {
        return $this->field('cid,gname,mprice,sprice,stock,describ,brand,norms,detail,gthumb,banner')->where('gid', $id)->find();
    }

    public function updates($data, $id)
    {
        return $this->where('gid', $id)->update($data);
    }

}