<?php

namespace app\index\controller;

use think\Controller;
use think\Exception;
use think\Request;

class Address extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        //
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
    }

    /**
     * 显示指定的资源
     *
     * @param  int $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
        $uid = $this->request->id;
        $ordersModel = model('Addressmodel');

        $res = $ordersModel->queryOne(['uid' => $uid, 'status' => 1]);

        if ($res) {
            return json([
                'code' => config('code.success'),
                'msg' => '获取成功',
                'data' => $res
            ]);
        } else {
            return json([
                'code' => config('code.fail'),
                'msg' => '获取失败',
            ]);
        }


    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request $request
     * @param  int $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
