<?php
/**
 * Created by PhpStorm.
 * User: 亮仔
 * Date: 2019/11/11
 * Time: 14:54
 */

namespace app\index\controller;


use think\Controller;
use think\Db;

class Cart extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }

    public function save()
    {
        //购物车添加商品
        //判断当前用户是否有购物车
        $uid = $this->request->id;  //用户id


        $data = $this->request->post();//获取数据   价格和商品id

        $gid = $data['gid'];
        $price = $data['price'];

        $model = model('Cartmodel');   //定义模型
        $cart = $model->queryone($uid);   //购物车的信息

        if ($cart) {
            //有购物车  判断购物车是否有商品
//            Db::startTrans();
            $cid = $cart['cid'];

            $extramodel = model('Cartextramodel');
            $goodsinfo = $extramodel->queryone(['uid' => $uid, 'gid' => $gid,]);

            //判断是否有商品，有的话直接加，没有的话插入一条
            if ($goodsinfo) {
                $IncRes = $extramodel->goodsnumInc(['uid' => $uid, 'gid' => $gid]);


            } else {
                $insertRes= $extramodel->insertgoods(['cid' => $cid, 'gid' => $gid, 'num' => 1, 'status' => 1, 'uid' => $uid]);


            }

            //total  price
            $numberInc = $model->cartInc($uid, 'total');
            $priceInc = $model->cartInc($uid, 'price', $price);

            if (($IncRes && $numberInc && $priceInc) || ($insertRes && $numberInc && $priceInc)) {
                Db::commit();
            } else {
                Db::rollback();
            }


        } else {


            //没有购物车，先创建，然后把数据插入到数据库中
            Db::startTrans();  //用到事务（手动的事务）
            $arr = ['id' => $uid, 'total' => 1, 'price' => $data['price']];  //初始化购物车

            $rows = $model->insertcart($arr);  //插入到数据库中
            $cid = $model->getLastInsID();
            $goods = ['cid' => $cid, 'gid' => $data['gid'], 'num' => 1, 'status' => 1, 'uid' => $uid];

            $result = Db::table('cart_extra')->insert($goods);
            if ($rows && $result) {
                Db::commit();
                return json([
                    'code' => config('code.success'),
                    'msg' => '购物车添加成功'
                ]);

            } else {
                Db::rollback();
            }

        }


    }

//    public function save()
//    {
//        $uid = $this->request->id;
//
//
//        //用户id
//        $data = $this->request->post();//获取数据
//        $gid = $data['gid'];
//        $sale = $data['sale'];
//        $model = model('Cartmodel');
//        $cart = $model->queryone($uid);
//
//        if ($cart) {
//            $cid = $cart['cid'];
//            $extramode = model('Cartextramodel');
//            $goodsInfo = $extramode->queryone(['uid' => $uid, 'gid' => $gid]);
//            if ($goodsInfo) {
//                $IncRes=$extramode->goodsnumInc(['uid' => $uid, 'gid' => $gid]);
//
//            } else {
//                $insertRes=$extramode->insertgoods(['uid' => $uid, 'num' => 1, 'status' => 1, 'gid' => $gid, 'cid' => $cid]);
//            }
//            $numInc=$model->cartInc($uid, 'total');
//            $priceInc=$model->cartInc($uid, 'price',$sale);
//            if (($IncRes && $numInc && $priceInc) || ($insertRes && $numInc && $priceInc)) {
//                Db::commit();
//            }else{
//                Db::rollback();
//            }
//        } else {
//            Db::startTrans();
//            $arr = ['id' => $uid, 'total' => 1, 'price' => $data['sale']];
//
//            $rows = $model->insertcart($arr);
//            $cid = $model->getLastInsID();
//            $goods = ['cid' => $cid, 'gid' => $data['gid'], 'num' => 1, 'status' => 1, 'uid' => $uid];
//
//            $result = Db::table('cart_extra')->insert($goods);
//            if ($rows && $result) {
//                Db::commit();
//                return json([
//                    'code' => config('code.success'),
//                    'msg' => '购物车添加成功'
//                ]);
//
//            } else {
//                Db::rollback();
//            }
//
//        }
//    }

}