<?php
/**
 * Created by PhpStorm.
 * User: 亮仔
 * Date: 2019/11/13
 * Time: 18:04
 */

namespace app\index\controller;


use think\Controller;
use think\Db;
use think\Request;

class Reduce extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }


    public function save(Request $request)
    {
        $uid = $this->request->id;  //用户id


        $data = $this->request->post();//获取数据   价格和商品id


        $gid = $data['gid'];
        $price = $data['price'];


        $model = model('Cartmodel');   //定义模型
        $extramodel = model('Cartextramodel');


        $goodsinfo = $extramodel->queryone(['uid' => $uid, 'gid' => $gid]);


        $IncRes = '';
        $insertRes='';
        if ($goodsinfo['num'] > 1) {
            $IncRes = $extramodel->goodsnumDec(['uid' => $uid, 'gid' => $gid]);

        } else {
            $insertRes = $extramodel->delectgoods(['uid' => $uid, 'gid' => $gid]);
        }

        $numberInc = $model->cartDec($uid, 'total');
        $priceInc = $model->cartDec($uid, 'price', $price);


        if (($IncRes && $numberInc && $priceInc) || ($insertRes && $numberInc && $priceInc)) {
            Db::commit();
            return json([
                'code' => config('code.success'),
                'msg' => '商品减少成功',
            ]);
        } else {
            Db::rollback();
            return json([
                'code' => config('code.fail'),
                'msg' => '商品减少失败'
            ]);
        }

    }

}